apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - env:
        - name: TEST_VAR1
          value: Patched
        - name: TEST_VAR2
          value: Additional
        image: nginx:1.15.2
        name: nginx
